#!/usr/bin/env ruby
begin
  require 'rubygems'
  require 'term/ansicolor'
  extend Term::ANSIColor
rescue LoadError
  def green(txt); txt; end
  alias :red :green
  alias :yellow :green
end

dotfiles_dir = File.dirname(__FILE__)
home_dir = ENV['HOME']

if not File.exist?(home_dir)
  puts "Could not find home directory"
  exit 1
end

Dir.entries(dotfiles_dir).reject{|f| f =~ /^\./ || f == File.basename(__FILE__)}.each do |f|
  dotfiles_path = File.expand_path(File.join(dotfiles_dir, f))
  dot_f = ".#{f}"
  home_path = File.join(home_dir, dot_f)
  if not File.exist?(home_path)
    begin
      File.symlink(dotfiles_path, home_path)
      puts "Link created:     #{green(dot_f)} -> #{dotfiles_path}"
    rescue
      puts red("Problem creating link: #{dot_f} -> #{dotfiles_path}")
    end
  elsif File.symlink?(home_path)
    if File.readlink(home_path) == dotfiles_path
      puts "Linked properly:  #{green(dot_f)}"
    else
      puts "Linked elsewhere: #{red(dot_f)}"
    end
  else
    puts "Regular file:     #{yellow(dot_f)}"
  end
end