#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if ! command -v starship &> /dev/null; then
  brew install starship
fi

mkdir -p ~/.config
ln -s "$SCRIPT_DIR/starship.toml" ~/.config/starship.toml
