#!/bin/sh

cd "$(dirname "$0")/.."
DOTFILES_DIR=$(pwd -P)

set -e

success() {
	printf "✅ $1\n"
}

fail() {
	printf "❌ $1\n"
	echo ''
	exit
}

link_file() {
	if [ -e "$2" ]; then
		if [ "$(readlink "$2")" = "$1" ]; then
			success "skipped $1"
			return 0
		else
			mv "$2" "$2.backup"
			success "moved $2 to $2.backup"
		fi
	fi
	ln -sf "$1" "$2"
	success "linked $1 to $2"
}


echo 'Symlinking dotfiles...'
find -H "$DOTFILES_DIR" -maxdepth 3 -name '*.symlink' -not -path '*.git*' |
	while read -r src; do
		dst="$HOME/.$(basename "${src%.*}")"
		link_file "$src" "$dst"
	done

link_file "$DOTFILES_DIR/bin" "$HOME/bin"

echo 'All dotfiles symlinked'
